# Test TLS/SSL connection to MongoDB
#
# docker compose -f docker/docker-compose-tls.yaml up -d

services:
  grafana:
    user: root
    container_name: mongodb-datasource-grafana-tls
    build:
      context: ../.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-11.2.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/haohanyang-mongodb-datasource
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/haohanyang-mongodb-datasource
      - ../certs:/certs:ro

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.haohanyang-mongodb-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: haohanyang-mongodb-datasource
    networks:
      - mongodb-datasource-tls

  mongo:
    image: mongo
    container_name: mongodb-datasource-mongo
    command:
      [--tlsMode, requireTLS, --tlsCertificateKeyFile, /certs/mongodb-server.pem, --tlsCAFile, /certs/ca-cert.pem]
    ports:
      - 27017:27017
    volumes:
      - ../certs:/certs:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - mongodb-datasource-tls

networks:
  mongodb-datasource-tls:
    driver: bridge
